// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ChEyh_ek1iHUFsvhujtMu9PR3QFIpHY',
    appId: '1:318883258619:web:a45ff39260b905a089505e',
    messagingSenderId: '318883258619',
    projectId: 'moviesapp-7e1b1',
    authDomain: 'moviesapp-7e1b1.firebaseapp.com',
    storageBucket: 'moviesapp-7e1b1.appspot.com',
    measurementId: 'G-H14D07G4MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL7Ma6908QwINd0XFG_3AnqyifbEC7V3Q',
    appId: '1:318883258619:android:07837b952cdf8b4f89505e',
    messagingSenderId: '318883258619',
    projectId: 'moviesapp-7e1b1',
    storageBucket: 'moviesapp-7e1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tlHbMrDosasHimMslV-fC4bIeXBMhUc',
    appId: '1:318883258619:ios:7777c3f2d856a99289505e',
    messagingSenderId: '318883258619',
    projectId: 'moviesapp-7e1b1',
    storageBucket: 'moviesapp-7e1b1.appspot.com',
    iosBundleId: 'com.example.movies_app6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tlHbMrDosasHimMslV-fC4bIeXBMhUc',
    appId: '1:318883258619:ios:7777c3f2d856a99289505e',
    messagingSenderId: '318883258619',
    projectId: 'moviesapp-7e1b1',
    storageBucket: 'moviesapp-7e1b1.appspot.com',
    iosBundleId: 'com.example.movies_app6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ChEyh_ek1iHUFsvhujtMu9PR3QFIpHY',
    appId: '1:318883258619:web:a428d7cff4b8534189505e',
    messagingSenderId: '318883258619',
    projectId: 'moviesapp-7e1b1',
    authDomain: 'moviesapp-7e1b1.firebaseapp.com',
    storageBucket: 'moviesapp-7e1b1.appspot.com',
    measurementId: 'G-CDM5JKT361',
  );
}
